{ lib, ... }:

{
  options.yubikeys = lib.mkOption {
    type = lib.types.listOf (lib.types.submodule {
      options = {
        serial = lib.mkOption {
          type = lib.types.str;
          description = "YubiKey serial number";
        };

        keyId = lib.mkOption {
          type = lib.types.str;
          description = "GPG key ID (short form)";
        };

        fingerprint = lib.mkOption {
          type = lib.types.str;
          description = "Full GPG key fingerprint";
        };

        sshKeygrip = lib.mkOption {
          type = lib.types.str;
          description = "SSH authentication key keygrip";
        };

        publicKeyPath = lib.mkOption {
          type = lib.types.path;
          description = "Path to GPG public key file (.asc)";
        };

        u2fKeyHandle = lib.mkOption {
          type = lib.types.str;
          description = "U2F key handle (generated by pamu2fcfg)";
        };

        u2fPublicKey = lib.mkOption {
          type = lib.types.str;
          description = "U2F public key (generated by pamu2fcfg)";
        };

        u2fAlgorithm = lib.mkOption {
          type = lib.types.str;
          default = "es256";
          description = "U2F algorithm (usually es256)";
        };

        u2fFlags = lib.mkOption {
          type = lib.types.str;
          default = "+presence";
          description = "U2F flags (usually +presence)";
        };
      };
    });
    default = [ ];
    description = "YubiKey configurations for this user";
  };
}
