# The pasta crash, INDUCED in the nix sandbox rather than asserted about.
#
# passt is built twice from the same source -- once as nixpkgs ships it, once
# with my/virtualisation/pasta's patch -- with tests/passt-null-flow-harness.c
# linked in, and the unpatched one MUST die of SIGSEGV. That direction is the
# point:
#
#   * a reproducer that stops reproducing proves nothing, so "the unpatched
#     build survived" is a FAILURE here. It is also how "nixpkgs carries the
#     upstream fix now" announces itself, instead of leaving a dead overlay in
#     the tree for the next reader to wonder about;
#   * if upstream instead restructures that hunk, the patch stops applying and
#     the patched build fails by name. Between the two, the overlay cannot rot
#     quietly in either direction.
#
# Loopback only, no privilege, no network: a connect() to 127.0.0.1:1 draws an
# ICMP port-unreachable, which arms SO_ERROR, which is all udp_sock_errs() needs
# to reach the logging call that dereferences the NULL flow.
{ lib
, nixpkgs
, system
, self
, inputs
}:

let
  testLib = import ./lib.nix { inherit lib nixpkgs system self inputs; };
  inherit (testLib) pkgs;

  # Built from plain nixpkgs' source on BOTH sides, so the difference between
  # the two derivations is exactly the patch and nothing about the overlay's
  # plumbing. Whether the overlay actually reaches pkgs.passt is a separate
  # question, answered in tests/virtualisation-containers.nix.
  harness = { name, patches }: pkgs.stdenv.mkDerivation {
    inherit name patches;
    inherit (pkgs.passt) src version;
    nativeBuildInputs = [ pkgs.gnumake pkgs.gawk pkgs.gnused ];
    dontConfigure = true;
    buildPhase = ''
      runHook preBuild

      # seccomp.h is generated by passt's own makefile from its source, and
      # udp.c includes it transitively.
      make seccomp.h

      cp ${./passt-null-flow-harness.c} crashtest.c

      # Everything except the translation units that carry a main() of their
      # own, plus udp.c -- which the harness #includes so it can reach the
      # static udp_sock_errs().
      srcs=$(ls ./*.c | grep -vE '^\./(passt|udp|qrap|passt-repair|pesto|crashtest)\.c$')

      # -O0 so the faulting load is not optimised away, and the same feature
      # macros passt's own build uses.
      $CC -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -DPAGE_SIZE=$(getconf PAGE_SIZE) \
        -DVERSION='"check"' -std=c11 -O0 -g -I. crashtest.c $srcs -o crashtest

      runHook postBuild
    '';
    installPhase = ''
      runHook preInstall
      install -Dm755 crashtest $out/bin/crashtest
      runHook postInstall
    '';
  };

  unpatched = harness { name = "passt-null-flow-unpatched"; patches = [ ]; };
  patched = harness {
    name = "passt-null-flow-patched";
    patches = [ ../my/virtualisation/pasta/udp-sock-errs-null-flow.patch ];
  };
in
{
  passt-null-flow = pkgs.runCommand "passt-null-flow" { } ''
    echo "== unpatched must SIGSEGV, or the reproducer is not driving the bug"
    rc=0
    ${unpatched}/bin/crashtest || rc=$?
    echo "unpatched exit=$rc"
    if [ "$rc" != 139 ]; then
      echo "FAIL: expected SIGSEGV (139) from unpatched udp_sock_errs(), got $rc." >&2
      echo "Either the reproducer no longer reaches the bug, or nixpkgs now carries" >&2
      echo "the upstream fix -- in which case my/virtualisation/pasta can be deleted" >&2
      echo "along with its line in platforms/linux.nix and this check." >&2
      exit 1
    fi

    echo "== patched must survive"
    if ! ${patched}/bin/crashtest; then
      echo "FAIL: the patched udp_sock_errs() still crashes" >&2
      exit 1
    fi

    echo "PASS: passt-null-flow" > $out
  '';
}
