# Option tree for the tailnet-private Radicle forge. An options FRAGMENT
# loaded through mkOptionsModule from platforms/linux.nix, like every other
# one-sided domain -- so the platforms file, and nothing else, is what decides
# that these options exist on Linux only. It lives in its own file rather than
# inside my/infra/options.nix because the tree is several times the size of
# k3s and github-runner combined.
#
# Deliberately NOT exposed:
#   - a freeform `services.radicle.settings` passthrough. The nixpkgs module
#     passes `--listen` on the command line, which silently overrides any
#     `node.listen` written through settings -- a passthrough would invite
#     exactly that trap. Exotic needs go through mkSystem's extraModules.
#   - `services.radicle.httpd.nginx`. Its non-null branch silently advertises
#     a PUBLIC DNS name in the node's externalAddresses and turns on
#     forceSSL + ACME -- the exact opposite of a tailnet-private forge.
{ lib, ... }:

{
  # Type-only second declaration of `my.infra`: my/infra/options.nix owns the
  # description and default, and duplicating those would collide. Submodule
  # TYPES merge, so this adds `radicle` to the existing option -- the same
  # shape my/hardware/biometrics/options.nix uses, and the shape CLAUDE.md
  # documents, so platforms/linux.nix is once again what decides the reach.
  infra = lib.mkOption {
    type = lib.types.submodule {
      options.radicle = lib.mkOption {
        description = "Self-hosted, tailnet-private Radicle forge";
        default = { };
        type = lib.types.submodule {
          options = {
            enable = lib.mkEnableOption "the Radicle node (tailnet-private forge member)";

            privateKeySecret = lib.mkOption {
              type = lib.types.str;
              default = "radicle/node-key";
              description = ''
                Name of the sops secret holding this machine's Radicle node private
                key (generated by `rad auth`, passphrase-less). Delivered to
                radicle-node via systemd LoadCredential; never lands in the store
                and never exists at a stable path outside the unit.

                Ignored when `privateKeyFile` is set.
              '';
            };

            privateKeyFile = lib.mkOption {
              type = lib.types.nullOr lib.types.path;
              default = null;
              example = "/var/lib/radicle-identity/node-key";
              description = ''
                Path to the node's private key, ALREADY DECRYPTED, delivered by
                something other than sops. Setting this suppresses the sops secret
                entirely -- not merely its use but its DECLARATION, because sops-nix
                runs `sops-install-secrets` whenever any secret is declared at all,
                so leaving it declared would still fail.

                This exists for one reason: **sops-nix cannot install secrets inside
                a rootless container.** It mounts a ramfs -- or a tmpfs under
                `sops.useTmpfs` -- at the secrets directory, and both are `mount(2)`,
                which needs `CAP_SYS_ADMIN`. A role that runs repository-supplied
                shell must not have that capability, so the two cannot be reconciled:
                decryption has to happen outside, on a host that does have it, with
                the plaintext bind-mounted in read-only.

                What matters is unchanged. The key is still encrypted at rest, still
                reaches radicle-node through `LoadCredential` (read as root before
                `User=` drops, so the radicle user never gets direct access), and
                still never enters the store. What differs is that the plaintext
                exists at a stable path for as long as the container runs, rather
                than only inside one unit's credentials directory -- which is already
                true of `/run/secrets` on every host that uses sops at all.

                On a machine that CAN mount, leave this null and use sops.
              '';
            };

            publicKey = lib.mkOption {
              type = lib.types.str;
              example = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBgFMhajUng+Rjj/sCFXI9PzG8BQjru2n7JgUVF1Kbv5";
              description = ''
                The node's public key (contents of `keys/radicle.pub`, WITHOUT any
                trailing comment). Public data; lives in the host layer in the clear.
              '';
            };

            node = {
              alias = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                description = "Node alias in gossip. Defaults to the hostname.";
              };

              listenPort = lib.mkOption {
                type = lib.types.port;
                default = 8776;
                description = "radicle-node P2P listen port (opened on tailscale0 only).";
              };

              listenAddress = lib.mkOption {
                type = lib.types.str;
                default = "[::]";
                description = ''
                  Listen address. The machine's tailscale IP is unknowable at eval
                  time, so the default binds every interface and relies on the
                  firewall: the port is opened on tailscale0 alone, every other
                  interface drops it.
                '';
              };

              connect = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                default = [ ];
                example = [ "z6Mkgv…@yoga.tailnet.ts.net:8776" ];
                description = ''
                  Static peer list, `<nid>@<host>:<port>`. A non-empty connect list
                  is what keeps the public bootstrap seeds (iris/rosa) out of the
                  address book entirely; the implementation additionally pins
                  `peers = static` so the node never dials anything else.
                '';
              };

              externalAddresses = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                default = [ ];
                example = [ "yoga.tailnet.ts.net:8776" ];
                description = ''
                  Addresses this node advertises in gossip. Tailnet MagicDNS names
                  only. Left empty, peers reach the node solely through their own
                  static `connect` entries.
                '';
              };

              defaultSeedingPolicy = lib.mkOption {
                type = lib.types.enum [ "block" "allow" ];
                default = "block";
                description = ''
                  config.json `seedingPolicy.default`. "block" seeds only what
                  `seedRepositories` (or a manual `rad seed`) names -- right for
                  workstations; "allow" seeds everything reachable -- right for the
                  fleet seed host.
                '';
              };
            };

            seedRepositories = lib.mkOption {
              default = [ ];
              description = ''
                Repositories this node seeds, declaratively (`rad seed` oneshot at
                activation -- administration without sudo).
              '';
              type = lib.types.listOf (lib.types.submodule {
                options = {
                  rid = lib.mkOption {
                    type = lib.types.str;
                    example = "rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5";
                    description = "Radicle repository id.";
                  };
                  scope = lib.mkOption {
                    type = lib.types.enum [ "all" "followed" ];
                    default = "all";
                    description = "Seeding scope: every peer's refs, or followed peers only.";
                  };
                };
              });
            };

            httpd = {
              enable = lib.mkEnableOption "radicle-httpd web view (tailnet-only)";

              listenPort = lib.mkOption {
                type = lib.types.port;
                # Not upstream's 8080: my.network.headscale defaults to 8080 and the
                # seed host is exactly where both are likely to run.
                default = 8780;
                description = "radicle-httpd port, opened on tailscale0 only.";
              };

              aliases = lib.mkOption {
                type = lib.types.attrsOf lib.types.str;
                default = { };
                example = { mynixos = "rad:z2y7KqUhUxZQ7Zhn1UNwmuMDtstTS"; };
                description = "Short-name -> RID aliases for clone URLs.";
              };

              # radicle-httpd is a JSON API, not a web page -- every path
              # answers application/json. The browsable forge is
              # radicle-explorer, a static SPA that CALLS that API. Serving our
              # own copy, rather than pointing a public explorer at this node,
              # is the whole point on a private network: no third-party
              # JavaScript ever sees the repositories.
              explorer = {
                enable = lib.mkEnableOption "the radicle-explorer web UI, served locally (tailnet-only)";

                listenPort = lib.mkOption {
                  type = lib.types.port;
                  default = 8781;
                  description = "Port for the explorer UI, opened on tailscale0 only.";
                };

                scheme = lib.mkOption {
                  type = lib.types.enum [ "http" "https" ];
                  default = "http";
                  description = ''
                    How the BROWSER reaches this explorer. "https" additionally
                    publishes it through `tailscale serve`, which terminates TLS
                    with the tailnet's own Let's Encrypt certificate -- so the
                    page is a secure context (no browser warning, and the web
                    APIs that require one keep working).

                    The tailnet is WireGuard-encrypted either way; this is about
                    what the browser is willing to do, not about the traffic
                    being readable.
                  '';
                };

                externalPort = lib.mkOption {
                  type = lib.types.port;
                  default = 443;
                  description = ''
                    Port the BROWSER connects to when scheme = "https" (the
                    `tailscale serve` front door). Ignored for plain http,
                    where listenPort is what the browser uses.
                  '';
                };

                # The explorer builds avatar URLs as
                # https://www.gravatar.com/avatar/<md5(email)>, so rendering a
                # commit list would have the BROWSER call gravatar.com with a
                # hash of each committer's address -- an outbound request, and
                # an identifier, leaving a forge that is otherwise private.
                # These serve the same images from this host instead, and the
                # implementation rewrites that URL so nothing external is ever
                # requested.
                # The explorer has no CI view: radicle-httpd serves repos,
                # nodes and stats, and CI results are job COBs it never reads.
                # The broker publishes its own HTML report pages instead, and
                # nothing serves them by default -- this puts them beside the
                # explorer so there is one place to look.
                ciReports = {
                  enable = lib.mkOption {
                    type = lib.types.bool;
                    default = true;
                    description = "Serve the CI broker's report pages under /ci/ (only when ci.enable).";
                  };

                  path = lib.mkOption {
                    type = lib.types.str;
                    default = "/ci/";
                    description = "URL path the reports are served under. Must end in a slash.";
                  };

                  proxyTo = lib.mkOption {
                    type = lib.types.nullOr lib.types.str;
                    default = null;
                    example = "http://radicle-x64-builder.tailnet.ts.net:8782/";
                    description = ''
                      Serve the reports by PROXYING to another node rather than
                      reading them from this machine's disk.

                      Needed the moment CI runs somewhere other than the machine
                      showing the explorer. Reports exist only on the builder
                      that produced them, and reaching them from here would mean
                      reading another container's filesystem across a userns
                      boundary -- matching subuid mappings by hand, which is
                      brittle in exactly the way this design avoids elsewhere.

                      With this set the local `report_dir` is not consulted, so
                      it works on a host whose own `ci.enable` is false. Without
                      it, a host that has stopped running CI serves an empty
                      directory listing: CI working perfectly and invisibly.
                    '';
                  };
                };

                avatars = {
                  enable = lib.mkOption {
                    type = lib.types.bool;
                    default = true;
                    description = "Serve avatars locally instead of from gravatar.com.";
                  };

                  default = lib.mkOption {
                    type = lib.types.nullOr lib.types.path;
                    default = null;
                    description = "Image shown for any address with no entry in byEmail.";
                  };

                  byEmail = lib.mkOption {
                    type = lib.types.attrsOf lib.types.path;
                    default = { };
                    example = lib.literalExpression ''{ "you@example.com" = ./avatar.png; }'';
                    description = ''
                      Address -> image. The file is published under the same
                      md5-of-lowercased-address name the explorer would have
                      asked gravatar for, so it resolves with no code change.
                      Use the address that appears in your COMMITS.
                    '';
                  };
                };

                seedHostname = lib.mkOption {
                  type = lib.types.nullOr lib.types.str;
                  default = null;
                  example = "yoga.tailnet-name.ts.net";
                  description = ''
                    Hostname the BROWSER uses to reach this seed's httpd API.
                    It is baked into the SPA at build time and fetched by the
                    browser, not the server, so "localhost" only works when the
                    browser runs on the seed itself -- use the tailnet name.
                    Defaults to the hostname.
                  '';
                };
              };
            };

            ci = {
              enable = lib.mkEnableOption "Radicle CI (broker + native adapters) on this node";

              # A role has no explorer and no httpd -- it serves no repositories
              # and reads none. Its CI reports still have to be reachable, and on
              # this fleet they are read off DISK, not from job COBs: the
              # explorer aliases report_dir directly.
              #
              # When CI moved into a container that quietly stopped working. The
              # seed's explorer still pointed at the SEED's report_dir, which no
              # longer receives anything, so /ci/ became an empty directory
              # listing rather than an error -- CI running correctly, invisibly.
              #
              # So a role serves its own reports and whatever fronts them proxies
              # to it. That keeps the files owned by the container's own user;
              # reading them from the host instead means matching subuid mappings
              # by hand across the boundary, which is the richest single source of
              # breakage in this design.
              serveReports = {
                enable = lib.mkOption {
                  type = lib.types.bool;
                  default = false;
                  description = ''
                    Serve this node's CI reports over HTTP, with no explorer and
                    no httpd. For a role whose reports are read by something
                    else -- a seed's explorer proxying to it.
                  '';
                };

                listenPort = lib.mkOption {
                  type = lib.types.port;
                  default = 8782;
                  description = ''
                    Port the reports are served on, opened on tailscale0 only
                    like every other port this domain uses.
                  '';
                };
              };

              trustedNids = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                default = [ ];
                example = [ "z6MkuEBniT9BRGVjKUUV2Yi8dcEHzbDAn1fD5meaZ33bNMJV" ];
                description = ''
                  NIDs whose pushes and patches may trigger CI. MANDATORY (asserted
                  non-empty): the broker runs repository-supplied shell, so without
                  a Node trigger filter anyone who can reach a seeded repo executes
                  arbitrary code on this host.
                '';
              };

              adapters = lib.mkOption {
                default = { native = { }; };
                description = "radicle-native-ci adapter instances, one broker trigger each.";
                type = lib.types.attrsOf (lib.types.submodule {
                  options = {
                    recipeFile = lib.mkOption {
                      type = lib.types.str;
                      default = ".radicle/native.yaml";
                      description = "Repo file whose presence (HasFile) gates this adapter.";
                    };
                    events = lib.mkOption {
                      type = lib.types.listOf lib.types.str;
                      default = [ "DefaultBranch" "PatchCreated" "PatchUpdated" ];
                      description = "Broker event names OR-ed into the trigger filter.";
                    };
                    extraRuntimePackages = lib.mkOption {
                      type = lib.types.listOf lib.types.package;
                      default = [ ];
                      description = ''
                        Added to the adapter PATH on top of upstream's base set; the
                        implementation always adds nix and the radicle-ci-build
                        helper itself.
                      '';
                    };
                  };
                });
              };
            };

            mirror = {
              enable = lib.mkEnableOption "event-driven GitHub mirroring (+ optional releases)";

              githubTokenFile = lib.mkOption {
                type = lib.types.nullOr lib.types.path;
                default = null;
                description = ''
                  Path to an ALREADY DECRYPTED GitHub token, placed there by
                  whatever runs this machine. The exact parallel of the node's
                  `privateKeyFile`, and for the same reason.

                  A ROLE CANNOT DECRYPT FOR ITSELF. sops-install-secrets mounts
                  a ramfs for its secrets directory, and systemd builds
                  `` by mounting -- so `sops.secrets` and
                  `LoadCredential`, which this module uses when this option is
                  null, both need CAP_SYS_ADMIN. A role running
                  repository-supplied shell must not have it. Decryption
                  therefore moves out to a host that does, and the plaintext is
                  bind-mounted in.

                  WHAT THAT COSTS, stated plainly: the token exists decrypted at
                  a stable path for as long as the container runs, rather than
                  only inside one unit's credentials directory. It is still
                  encrypted at rest and still never enters the store. It is also
                  an argument for the mirror being the only extra thing a seed
                  ever runs -- the seed's own key is expensive to rotate, and
                  every additional process beside it widens what a compromise
                  reaches.
                '';
              };

              githubTokenSecret = lib.mkOption {
                type = lib.types.str;
                default = "radicle/github-token";
                description = ''
                  sops secret name for a GitHub fine-grained PAT (Contents: Read &
                  Write on exactly the mirrored repos). LoadCredential into the
                  mirror units only.
                '';
              };

              sourceNid = lib.mkOption {
                type = lib.types.str;
                example = "z6MkuEBniT9BRGVjKUUV2Yi8dcEHzbDAn1fD5meaZ33bNMJV";
                description = ''
                  Default delegate NID whose signed view is mirrored. Storage keeps
                  only the canonical default branch at top level; every other branch
                  and all tags exist solely inside per-peer namespaces, so a mirror
                  must name whose namespace is truth.
                '';
              };

              safetyInterval = lib.mkOption {
                type = lib.types.str;
                default = "hourly";
                description = ''
                  systemd OnCalendar for the safety-net timer. Mirroring is
                  event-driven (path units watching each repo's sigrefs); the timer
                  catches missed events and retries failed release uploads.
                '';
              };

              notifyCommand = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                example = "curl -fsS -d \"radicle mirror failed: $MIRROR_UNIT\" https://ntfy.example/topic";
                description = ''
                  Shell command run when a mirror unit fails ($MIRROR_UNIT names
                  it). Null leaves failures visible only in `systemctl --failed`
                  and the journal.
                '';
              };

              repos = lib.mkOption {
                default = [ ];
                description = "Repositories to mirror to GitHub.";
                type = lib.types.listOf (lib.types.submodule {
                  options = {
                    rid = lib.mkOption {
                      type = lib.types.str;
                      example = "rad:z2y7KqUhUxZQ7Zhn1UNwmuMDtstTS";
                      description = "Radicle repository id.";
                    };
                    githubRepo = lib.mkOption {
                      type = lib.types.str;
                      example = "i-am-logger/mynixos";
                      description = "GitHub owner/name to push to (repo must already exist).";
                    };
                    sourceNid = lib.mkOption {
                      type = lib.types.nullOr lib.types.str;
                      default = null;
                      description = "Override of mirror.sourceNid for this repo.";
                    };
                    pushTags = lib.mkOption {
                      type = lib.types.bool;
                      default = true;
                      description = "Mirror tags as well as branches.";
                    };
                    releases = {
                      enable = lib.mkEnableOption "GitHub releases for new v* tags";
                      systems = lib.mkOption {
                        type = lib.types.listOf lib.types.str;
                        default = [ ];
                        example = [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" ];
                        description = ''
                          Systems whose release artifact is built and attached
                          (`packages.<system>.<attribute>` of the pushed tag,
                          built from the GitHub ref so the release is exactly what
                          was published). Empty list = release with notes only.
                          aarch64-darwin requires the remote builder to be awake;
                          a failed release build is retried by the safety timer.
                        '';
                      };
                      attribute = lib.mkOption {
                        type = lib.types.str;
                        default = "default";
                        description = "Package attribute under packages.<system> to build.";
                      };
                    };
                  };
                });
              };
            };
          };
        };
      };
    };
  };
}
