# Option tree for the tailnet-private Radicle forge. An options FRAGMENT
# loaded through mkOptionsModule from platforms/linux.nix, like every other
# one-sided domain -- so the platforms file, and nothing else, is what decides
# that these options exist on Linux only. It lives in its own file rather than
# inside my/infra/options.nix because the tree is several times the size of
# k3s and github-runner combined.
#
# Deliberately NOT exposed:
#   - a freeform `services.radicle.settings` passthrough. The nixpkgs module
#     passes `--listen` on the command line, which silently overrides any
#     `node.listen` written through settings -- a passthrough would invite
#     exactly that trap. Exotic needs go through mkSystem's extraModules.
#   - `services.radicle.httpd.nginx`. Its non-null branch silently advertises
#     a PUBLIC DNS name in the node's externalAddresses and turns on
#     forceSSL + ACME -- the exact opposite of a tailnet-private forge.
{ lib, ... }:

{
  # Type-only second declaration of `my.infra`: my/infra/options.nix owns the
  # description and default, and duplicating those would collide. Submodule
  # TYPES merge, so this adds `radicle` to the existing option -- the same
  # shape my/hardware/biometrics/options.nix uses, and the shape CLAUDE.md
  # documents, so platforms/linux.nix is once again what decides the reach.
  infra = lib.mkOption {
    type = lib.types.submodule {
      options.radicle = lib.mkOption {
        description = "Self-hosted, tailnet-private Radicle forge";
        default = { };
        type = lib.types.submodule {
          options = {
            enable = lib.mkEnableOption "the Radicle node (tailnet-private forge member)";

            privateKeySecret = lib.mkOption {
              type = lib.types.str;
              default = "radicle/node-key";
              description = ''
                Name of the sops secret holding this machine's Radicle node private
                key (generated by `rad auth`, passphrase-less). Delivered to
                radicle-node via systemd LoadCredential; never lands in the store
                and never exists at a stable path outside the unit.
              '';
            };

            publicKey = lib.mkOption {
              type = lib.types.str;
              example = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBgFMhajUng+Rjj/sCFXI9PzG8BQjru2n7JgUVF1Kbv5";
              description = ''
                The node's public key (contents of `keys/radicle.pub`, WITHOUT any
                trailing comment). Public data; lives in the host layer in the clear.
              '';
            };

            node = {
              alias = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                description = "Node alias in gossip. Defaults to the hostname.";
              };

              listenPort = lib.mkOption {
                type = lib.types.port;
                default = 8776;
                description = "radicle-node P2P listen port (opened on tailscale0 only).";
              };

              listenAddress = lib.mkOption {
                type = lib.types.str;
                default = "[::]";
                description = ''
                  Listen address. The machine's tailscale IP is unknowable at eval
                  time, so the default binds every interface and relies on the
                  firewall: the port is opened on tailscale0 alone, every other
                  interface drops it.
                '';
              };

              connect = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                default = [ ];
                example = [ "z6Mkgv…@yoga.tailnet.ts.net:8776" ];
                description = ''
                  Static peer list, `<nid>@<host>:<port>`. A non-empty connect list
                  is what keeps the public bootstrap seeds (iris/rosa) out of the
                  address book entirely; the implementation additionally pins
                  `peers = static` so the node never dials anything else.
                '';
              };

              externalAddresses = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                default = [ ];
                example = [ "yoga.tailnet.ts.net:8776" ];
                description = ''
                  Addresses this node advertises in gossip. Tailnet MagicDNS names
                  only. Left empty, peers reach the node solely through their own
                  static `connect` entries.
                '';
              };

              defaultSeedingPolicy = lib.mkOption {
                type = lib.types.enum [ "block" "allow" ];
                default = "block";
                description = ''
                  config.json `seedingPolicy.default`. "block" seeds only what
                  `seedRepositories` (or a manual `rad seed`) names -- right for
                  workstations; "allow" seeds everything reachable -- right for the
                  fleet seed host.
                '';
              };
            };

            seedRepositories = lib.mkOption {
              default = [ ];
              description = ''
                Repositories this node seeds, declaratively (`rad seed` oneshot at
                activation -- administration without sudo).
              '';
              type = lib.types.listOf (lib.types.submodule {
                options = {
                  rid = lib.mkOption {
                    type = lib.types.str;
                    example = "rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5";
                    description = "Radicle repository id.";
                  };
                  scope = lib.mkOption {
                    type = lib.types.enum [ "all" "followed" ];
                    default = "all";
                    description = "Seeding scope: every peer's refs, or followed peers only.";
                  };
                };
              });
            };

            httpd = {
              enable = lib.mkEnableOption "radicle-httpd web view (tailnet-only)";

              listenPort = lib.mkOption {
                type = lib.types.port;
                # Not upstream's 8080: my.network.headscale defaults to 8080 and the
                # seed host is exactly where both are likely to run.
                default = 8780;
                description = "radicle-httpd port, opened on tailscale0 only.";
              };

              aliases = lib.mkOption {
                type = lib.types.attrsOf lib.types.str;
                default = { };
                example = { mynixos = "rad:z2y7KqUhUxZQ7Zhn1UNwmuMDtstTS"; };
                description = "Short-name -> RID aliases for clone URLs.";
              };
            };

            ci = {
              enable = lib.mkEnableOption "Radicle CI (broker + native adapters) on this node";

              trustedNids = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                default = [ ];
                example = [ "z6MkuEBniT9BRGVjKUUV2Yi8dcEHzbDAn1fD5meaZ33bNMJV" ];
                description = ''
                  NIDs whose pushes and patches may trigger CI. MANDATORY (asserted
                  non-empty): the broker runs repository-supplied shell, so without
                  a Node trigger filter anyone who can reach a seeded repo executes
                  arbitrary code on this host.
                '';
              };

              adapters = lib.mkOption {
                default = { native = { }; };
                description = "radicle-native-ci adapter instances, one broker trigger each.";
                type = lib.types.attrsOf (lib.types.submodule {
                  options = {
                    recipeFile = lib.mkOption {
                      type = lib.types.str;
                      default = ".radicle/native.yaml";
                      description = "Repo file whose presence (HasFile) gates this adapter.";
                    };
                    events = lib.mkOption {
                      type = lib.types.listOf lib.types.str;
                      default = [ "DefaultBranch" "PatchCreated" "PatchUpdated" ];
                      description = "Broker event names OR-ed into the trigger filter.";
                    };
                    extraRuntimePackages = lib.mkOption {
                      type = lib.types.listOf lib.types.package;
                      default = [ ];
                      description = ''
                        Added to the adapter PATH on top of upstream's base set; the
                        implementation always adds nix and the radicle-ci-build
                        helper itself.
                      '';
                    };
                  };
                });
              };
            };

            mirror = {
              enable = lib.mkEnableOption "event-driven GitHub mirroring (+ optional releases)";

              githubTokenSecret = lib.mkOption {
                type = lib.types.str;
                default = "radicle/github-token";
                description = ''
                  sops secret name for a GitHub fine-grained PAT (Contents: Read &
                  Write on exactly the mirrored repos). LoadCredential into the
                  mirror units only.
                '';
              };

              sourceNid = lib.mkOption {
                type = lib.types.str;
                example = "z6MkuEBniT9BRGVjKUUV2Yi8dcEHzbDAn1fD5meaZ33bNMJV";
                description = ''
                  Default delegate NID whose signed view is mirrored. Storage keeps
                  only the canonical default branch at top level; every other branch
                  and all tags exist solely inside per-peer namespaces, so a mirror
                  must name whose namespace is truth.
                '';
              };

              safetyInterval = lib.mkOption {
                type = lib.types.str;
                default = "hourly";
                description = ''
                  systemd OnCalendar for the safety-net timer. Mirroring is
                  event-driven (path units watching each repo's sigrefs); the timer
                  catches missed events and retries failed release uploads.
                '';
              };

              notifyCommand = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                example = "curl -fsS -d \"radicle mirror failed: $MIRROR_UNIT\" https://ntfy.example/topic";
                description = ''
                  Shell command run when a mirror unit fails ($MIRROR_UNIT names
                  it). Null leaves failures visible only in `systemctl --failed`
                  and the journal.
                '';
              };

              repos = lib.mkOption {
                default = [ ];
                description = "Repositories to mirror to GitHub.";
                type = lib.types.listOf (lib.types.submodule {
                  options = {
                    rid = lib.mkOption {
                      type = lib.types.str;
                      example = "rad:z2y7KqUhUxZQ7Zhn1UNwmuMDtstTS";
                      description = "Radicle repository id.";
                    };
                    githubRepo = lib.mkOption {
                      type = lib.types.str;
                      example = "i-am-logger/mynixos";
                      description = "GitHub owner/name to push to (repo must already exist).";
                    };
                    sourceNid = lib.mkOption {
                      type = lib.types.nullOr lib.types.str;
                      default = null;
                      description = "Override of mirror.sourceNid for this repo.";
                    };
                    pushTags = lib.mkOption {
                      type = lib.types.bool;
                      default = true;
                      description = "Mirror tags as well as branches.";
                    };
                    releases = {
                      enable = lib.mkEnableOption "GitHub releases for new v* tags";
                      systems = lib.mkOption {
                        type = lib.types.listOf lib.types.str;
                        default = [ ];
                        example = [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" ];
                        description = ''
                          Systems whose release artifact is built and attached
                          (`packages.<system>.<attribute>` of the pushed tag,
                          built from the GitHub ref so the release is exactly what
                          was published). Empty list = release with notes only.
                          aarch64-darwin requires the remote builder to be awake;
                          a failed release build is retried by the safety timer.
                        '';
                      };
                      attribute = lib.mkOption {
                        type = lib.types.str;
                        default = "default";
                        description = "Package attribute under packages.<system> to build.";
                      };
                    };
                  };
                });
              };
            };
          };
        };
      };
    };
  };
}
