{ lib, ... }:

{
  options.yubikeys = lib.mkOption {
    type = lib.types.listOf (lib.types.submodule {
      options = {
        serial = lib.mkOption {
          type = lib.types.str;
          description = "YubiKey serial number";
        };

        keyId = lib.mkOption {
          type = lib.types.str;
          description = "GPG key ID (short form)";
        };

        fingerprint = lib.mkOption {
          type = lib.types.str;
          description = "Full GPG key fingerprint";
        };

        sshKeygrip = lib.mkOption {
          type = lib.types.str;
          description = "SSH authentication key keygrip";
        };

        sshPublicKey = lib.mkOption {
          type = lib.types.str;
          default = "";
          description = "SSH public key string (ssh-ed25519 AAAA... or ssh-rsa AAAA...) for authorized_keys";
        };

        publicKeyPath = lib.mkOption {
          type = lib.types.path;
          description = "Path to GPG public key file (.asc)";
        };

        u2fKeyHandle = lib.mkOption {
          type = lib.types.str;
          description = "U2F key handle (generated by pamu2fcfg)";
        };

        u2fPublicKey = lib.mkOption {
          type = lib.types.str;
          description = "U2F public key (generated by pamu2fcfg)";
        };

        # COSE algorithm captured at registration (pamu2fcfg). The pam-u2f
        # authfile only accepts these three COSE types, so a typo here would
        # silently break auth — constrain it.
        u2fAlgorithm = lib.mkOption {
          type = lib.types.enum [ "es256" "rs256" "eddsa" ];
          default = "es256";
          description = "U2F/FIDO2 COSE algorithm (es256 is the YubiKey default)";
        };

        # Free-form on purpose: pam-u2f flags are a combinable token set
        # (e.g. "+presence", "+pin", "+verification", or combinations), so this
        # is NOT a closed enum.
        u2fFlags = lib.mkOption {
          type = lib.types.str;
          default = "+presence";
          description = "U2F flags, combinable pam-u2f tokens (usually +presence)";
        };
      };
    });
    default = [ ];
    description = "YubiKey configurations for this user";
  };
}
